insert into tb_usuarios (balance, document, email, name, type) values (0, '753.471.110-01', 'marcosviniciusdarocha@advogadostb.com.br', 'Tacoy', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '157.032.570-77', 'otavio-rocha80@prudential.com', 'Erfya', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '350.612.100-69', 'marcos_caio_dapaz@yahoo.com.br', 'Paoxa', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '643.258.640-24', 'diego.fernando.viana@editorazap.com.br', 'Cluvi', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '254.153.430-24', 'caio-aparicio77@jerasistemas.com.br', 'Bredo', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '202.586.840-54', 'jorge-assis78@taclog.com.br', 'Flonelel', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '833.334.310-41', 'caiosamuelferreira@hotmailo.com', 'Fayfa', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '175.532.120-16', 'lorenzo.diogo.melo@sociedadeweb.com.br', 'Xiezaubi', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '364.521.740-10', 'caue_baptista@moncoes.com.br', 'Hoeir', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '086.923.560-50', 'andre.pedro.dossantos@elconsultoria.com.br', 'Zerica', 'USUARIOS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '70.311.193/0001-87', 'corrie1498@uorak.com', 'Severino e Luana Filmagens ME', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '52.822.994/0001-25', 'cobranca@arthurefranciscocomerciodebebidasme.com.br', 'Fabiana e Ana Vidros Ltda', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '41.952.519/0001-57', 'auditoria@thalesefernandofinanceiraltda.com.br', 'Manuel e Renan Publicidade e Propaganda Ltda', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '16.134.777/0001-89', 'estoque@muriloeyagoconstrucoesme.com.br', 'Fábio e Murilo Comercio de Bebidas ME', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '41.997.024/0001-44', 'estoque@andreecarlosfotografiasme.com.br', 'Regina e Cauê Assessoria Jurídica Ltda', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '90.974.224/0001-97', 'tesouraria@enricoetiagograficaltda.com.br', 'Josefa e Marcos Telecom ME', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '93.512.481/0001-03', 'sistema@pietraegiovannacomerciodebebidasltda.com.br', 'Lívia e Carlos Eduardo Transportes ME', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '11.356.354/0001-90', 'presidencia@marceloeenzopaesedocesme.com.br', 'Yago e Tânia Restaurante ME', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '14.501.501/0001-66', 'estoque@lauraecamilamudancasltda.com.br', 'Yago e Murilo Telecomunicações ME', 'LOGISTAS');
insert into tb_usuarios (balance, document, email, name, type) values (0, '10.566.333/0001-36', 'presidencia@oliverecauaesportesme.com.br', 'Malu e Cecília Contábil ME', 'LOGISTAS');